# -*- coding: utf-8 -*-
"""web_simple_vrp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7bIUAdeIrOLzwylbL8nCnQKnH2NPcCG
"""

!pip install streamlit ortools

# Commented out IPython magic to ensure Python compatibility.
# %%writefile web_simple_vrp.py
# import streamlit as st
# from ortools.constraint_solver import routing_enums_pb2
# from ortools.constraint_solver import pywrapcp
# 
# # Đồ án cuối kỳ - Môn Optimization
# # Đề tài: Simple Vehicle Routing Problem (VRP)
# # Nhóm thực hiện: 2 sinh viên
# 
# def main():
#     st.set_page_config(page_title="Demo VRP", layout="centered")
#     st.title("🚛 Demo VRP - Đồ án Optimization")
#     st.caption("Ứng dụng tìm đường đi ngắn nhất cho đội xe (Simple VRP)")
#     st.markdown("---")
# 
#     if st.button("Chạy thuật toán OR-Tools"):
#         # Data fix cứng để demo báo cáo
#         # Ma trận khoảng cách giữa kho (0) và 4 khách hàng
#         matrix_khoang_cach = [
#             [0, 548, 776, 696, 582],
#             [548, 0, 684, 308, 194],
#             [776, 684, 0, 992, 878],
#             [696, 308, 992, 0, 114],
#             [582, 194, 878, 114, 0],
#         ]
#         so_xe = 2
#         kho_xuat_phat = 0
# 
#         # Khai báo model theo docs của google
#         manager = pywrapcp.RoutingIndexManager(len(matrix_khoang_cach), so_xe, kho_xuat_phat)
#         routing = pywrapcp.RoutingModel(manager)
# 
#         # Hàm này để model tra cứu khoảng cách
#         def distance_callback(from_index, to_index):
#             node_a = manager.IndexToNode(from_index)
#             node_b = manager.IndexToNode(to_index)
#             return matrix_khoang_cach[node_a][node_b]
# 
#         transit_callback_index = routing.RegisterTransitCallback(distance_callback)
#         routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)
# 
#         # Setup tham số, xài heuristic đường rẻ nhất
#         search_params = pywrapcp.DefaultRoutingSearchParameters()
#         search_params.first_solution_strategy = routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
# 
#         # Giải bài toán
#         solution = routing.SolveWithParameters(search_params)
# 
#         # print("Debug: solution =", solution) # Cố tình để lại comment debug
# 
#         if solution:
#             st.success(f"Đã giải xong! Tổng quãng đường: {solution.ObjectiveValue()} m")
# 
#             # Quét từng xe để in lộ trình lên UI
#             for xe in range(so_xe):
#                 index = routing.Start(xe)
#                 route_str = f"**Xe {xe}:** Kho 0 "
#                 route_dist = 0
# 
#                 while not routing.IsEnd(index):
#                     prev_index = index
#                     index = solution.Value(routing.NextVar(index))
#                     route_dist += routing.GetArcCostForVehicle(prev_index, index, xe)
#                     route_str += f" ➡️ Node {manager.IndexToNode(index)}"
# 
#                 st.info(route_str)
#                 st.write(f"*Quãng đường xe này đi:* {route_dist} m")
#         else:
#             st.error("Lỗi: Thuật toán không tìm ra kết quả, check lại ràng buộc!")
# 
# if __name__ == '__main__':
#     main()

!wget -q -O - ipv4.icanhazip.com
!streamlit run web_simple_vrp.py & npx --yes localtunnel --port 8501